{% set name = "limix-inference" %}
{% set version = "1.0.9" %}
{% set sha256 = "7398a7a2c1d7282aab49be46c72f776256487251123fd9711a78e4fec712dd5f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 6
  skip: True  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - ncephes
    - liknorm >=1.2.3
  run:
    - python
    - ncephes
    - optimix >=1.1.5
    - numpy >=1.9.2
    - scipy
    - numpy-sugar
    - cachetools >=2.0
    - tqdm >=4
    - liknorm >=1.2.3
    - scipy-sugar >=1.0.1

test:
  requires:
    - pytest >=3
  imports:
    - limix_inference
  commands:
    - python -c "import sys; import limix_inference; sys.exit(limix_inference.test())"

about:
  home: http://github.com/glimix/limix-inference
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fast inference for Generalized Linear Mixed Models'
  doc_url: http://limix-inference.readthedocs.io/
  dev_url: https://github.com/glimix/limix-inference

extra:
  recipe-maintainers:
    - Horta
