{% set name = "limix-inference" %}
{% set version = "1.1.4" %}
{% set sha256 = "e866c0022d9bbf0c9ebe7c5984c6793075391cc88b6b1317fef7b7287b72ee9e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - ncephes
    - liknorm >=1.2.3
  run:
    - python
    - ncephes >=1.0.21
    - optimix >=1.2.5
    - numpy >=1.9.2
    - scipy >=0.19
    - numpy-sugar >=1.0.28
    - cachetools >=2.0
    - tqdm >=4
    - liknorm >=1.2.3
    - scipy-sugar >=1.0.1

test:
  requires:
    - pytest >=3
  imports:
    - limix_inference
  commands:
    - python -c "import sys; import limix_inference; sys.exit(limix_inference.test())"

about:
  home: http://github.com/glimix/limix-inference
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fast inference for Generalized Linear Mixed Models'
  doc_url: http://limix-inference.readthedocs.io/
  dev_url: https://github.com/glimix/limix-inference

extra:
  recipe-maintainers:
    - Horta
