appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: R/U4f5rGwGPGCOT5mwJyqbzW6zY1g6NvEzTpmjZYREOnuZ3LscFLAQjQryBE2Bk0KjGk9wvTrtv2Nqsezq6l1qvdFqFOD3BsrksCEKSkz+NiutjaHWyPsbWUYxaGp8BY0sI38E7qUgrTxirRJNJS2LqI3r85AkbcGDAIHo/5y8YPFMNL98vHyh5DIkz8F6K4CBcg9S/XU4HVe98ZLI1fL3g1RJxvtvtQxuR5bDai6iztxxTueTiUERNcjRpM2yei3XYZ3HmEr7uRD6pC6soNbas07fIj/EdQKUTODcw1Q5oFOiJ1i5zjWGLWdhLF4Ej7Axkz4zlMYJ4LdFelFwcnETWxg81Z6LKWO6I1X0zf5AUU/FjY3X8VzEeGS1Nj0jiITPofuez34FvItMvXLzzahlWdY+xytI7FzZvlwLUzT+0jtBJeiLquBWIBV5Y+DqlRW61WT4Mb6YENpxaSPy8eYnWkGK1gDHjcm+bNe9si1FACF2oYXd2nqyknRO0pUmsNbgffUi/nybXaeUhY8dy0n+4o2SwlBKNj15ATXJKSf83JTV9R3EmNCHHLVXly/y+N3JdZvubikTT1rsrmqKQ8Dgshw9hGX4rLEOkUKjjSKvciCgir2ylog89WFEYat/A0x9ukRD8blfH9ZPTsF8g0pETt6SToeVkf1doYW8ETPjI=}
