travis:
  secure:
    BINSTAR_TOKEN: J0WWh+3zATnxqFJuksfW+LXFZ7w00DeNY1fBbbMYYFGvZlZX5th6PmyjOxaLCMZj+p/tBQ0mM3ZE0ikPy2gp0nI4AzhutnZv11xj3T6H8adYRd1K5rt1MI9EP8iw4TEYbjUA2/xMxAr5LVqoD1Emtg/oRhyHViKRM8GtbzyPWeFjSg0nv338+VyuDnQO90XFonWRdGCqi/DNi3PrUyHZOS6cXOadvJG6r2q3rl3luIyAUL+YG8OAOK0myOa2dnQiD+UbYBEyzkT1dY9mUuOUa7L0M3X5SAafg/RPalxerl7Z94UmxPi72YhWKAOOzinmx4/Zipc4Dc+R3ORVvG77Su2APmx4sD38iHNKqC52ptBnIFx45qzyiun2UfIKF8Bd3AjX09SAdbKngPqUacBePsWqjUGfISnvJCl8SatxNFBFTfJP5kFiQy25+u1wWEFS3RMl6D8i++Gu1grUeh/RlenbXfCfsTdHhCNvGMqZtO+2gzZuH0W8LG9j8qQ3GaTavJsIw4yso2a+UcDhqD4/At1Mmn47GtRpBs9p8+o+hMVvR5q9ZlEq7ptAmeSO+O4gjY+MmNyEHFPWGuv4/aiBE/Zl9yeNPU51igVJxog24E9rOuPmBixJTz4yeqWB3uXlUFV2pF+RUMPCNqYhuXUZlYjq9kXGShd2SpmbLTGjv50=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
